/* Auto-generated by scripts/fetch-edit-fonts.mjs - do not edit by hand. */
import type { EditFont } from "./editFonts";

export const GENERATED_FONTS: EditFont[] = [
  {
    "id": "arimo",
    "label": "Arial / Helvetica (Arimo)",
    "family": "\"MD Arimo\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "tinos",
    "label": "Times New Roman (Tinos)",
    "family": "\"MD Tinos\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "cousine",
    "label": "Courier New (Cousine)",
    "family": "\"MD Cousine\"",
    "cls": "mono",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "carlito",
    "label": "Calibri (Carlito)",
    "family": "\"MD Carlito\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "caladea",
    "label": "Cambria (Caladea)",
    "family": "\"MD Caladea\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "roboto",
    "label": "Roboto",
    "family": "\"MD Roboto\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "opensans",
    "label": "Open Sans",
    "family": "\"MD Open Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "lato",
    "label": "Lato",
    "family": "\"MD Lato\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "inter",
    "label": "Inter / San Francisco-like",
    "family": "\"MD Inter\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "sourcesans",
    "label": "Source Sans",
    "family": "\"MD Source Sans 3\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "notosans",
    "label": "Noto Sans",
    "family": "\"MD Noto Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "montserrat",
    "label": "Montserrat",
    "family": "\"MD Montserrat\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "poppins",
    "label": "Poppins",
    "family": "\"MD Poppins\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "raleway",
    "label": "Raleway",
    "family": "\"MD Raleway\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "nunito",
    "label": "Nunito",
    "family": "\"MD Nunito\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "nunitosans",
    "label": "Nunito Sans",
    "family": "\"MD Nunito Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "ptsans",
    "label": "PT Sans",
    "family": "\"MD PT Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "worksans",
    "label": "Work Sans",
    "family": "\"MD Work Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "rubik",
    "label": "Rubik",
    "family": "\"MD Rubik\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "firasans",
    "label": "Fira Sans",
    "family": "\"MD Fira Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "ubuntu",
    "label": "Ubuntu",
    "family": "\"MD Ubuntu\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "barlow",
    "label": "Barlow",
    "family": "\"MD Barlow\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "dmsans",
    "label": "DM Sans",
    "family": "\"MD DM Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "manrope",
    "label": "Manrope",
    "family": "\"MD Manrope\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "mulish",
    "label": "Mulish",
    "family": "\"MD Mulish\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "josefinsans",
    "label": "Josefin Sans",
    "family": "\"MD Josefin Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "quicksand",
    "label": "Quicksand",
    "family": "\"MD Quicksand\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "kanit",
    "label": "Kanit",
    "family": "\"MD Kanit\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "cabin",
    "label": "Cabin",
    "family": "\"MD Cabin\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "titillium",
    "label": "Titillium Web",
    "family": "\"MD Titillium Web\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "exo2",
    "label": "Exo 2",
    "family": "\"MD Exo 2\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "librefranklin",
    "label": "Libre Franklin (Franklin Gothic)",
    "family": "\"MD Libre Franklin\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "plexsans",
    "label": "IBM Plex Sans",
    "family": "\"MD IBM Plex Sans\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "karla",
    "label": "Karla",
    "family": "\"MD Karla\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "spacegrotesk",
    "label": "Space Grotesk",
    "family": "\"MD Space Grotesk\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "outfit",
    "label": "Outfit",
    "family": "\"MD Outfit\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "figtree",
    "label": "Figtree",
    "family": "\"MD Figtree\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "archivo",
    "label": "Archivo",
    "family": "\"MD Archivo\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "heebo",
    "label": "Heebo",
    "family": "\"MD Heebo\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "hind",
    "label": "Hind",
    "family": "\"MD Hind\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "asap",
    "label": "Asap",
    "family": "\"MD Asap\"",
    "cls": "sans",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "signika",
    "label": "Signika",
    "family": "\"MD Signika\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "varelaround",
    "label": "Varela Round",
    "family": "\"MD Varela Round\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "comfortaa",
    "label": "Comfortaa",
    "family": "\"MD Comfortaa\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "fredoka",
    "label": "Fredoka (rounded)",
    "family": "\"MD Fredoka\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "baloo2",
    "label": "Baloo 2",
    "family": "\"MD Baloo 2\"",
    "cls": "sans",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "oswald",
    "label": "Oswald (condensed)",
    "family": "\"MD Oswald\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "bebasneue",
    "label": "Bebas Neue",
    "family": "\"MD Bebas Neue\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "anton",
    "label": "Anton / Impact-like",
    "family": "\"MD Anton\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "archivoblack",
    "label": "Archivo Black",
    "family": "\"MD Archivo Black\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "barlowcondensed",
    "label": "Barlow Condensed",
    "family": "\"MD Barlow Condensed\"",
    "cls": "display",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "fjallaone",
    "label": "Fjalla One",
    "family": "\"MD Fjalla One\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "teko",
    "label": "Teko",
    "family": "\"MD Teko\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "staatliches",
    "label": "Staatliches",
    "family": "\"MD Staatliches\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "passionone",
    "label": "Passion One",
    "family": "\"MD Passion One\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "righteous",
    "label": "Righteous",
    "family": "\"MD Righteous\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "russoone",
    "label": "Russo One",
    "family": "\"MD Russo One\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "lilitaone",
    "label": "Lilita One",
    "family": "\"MD Lilita One\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "bangers",
    "label": "Bangers (comic)",
    "family": "\"MD Bangers\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "luckiestguy",
    "label": "Luckiest Guy",
    "family": "\"MD Luckiest Guy\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "alfaslab",
    "label": "Alfa Slab One",
    "family": "\"MD Alfa Slab One\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "abrilfatface",
    "label": "Abril Fatface",
    "family": "\"MD Abril Fatface\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "dmserifdisplay",
    "label": "DM Serif Display",
    "family": "\"MD DM Serif Display\"",
    "cls": "display",
    "hasItalic": true,
    "hasBold": false
  },
  {
    "id": "cinzel",
    "label": "Cinzel (Trajan-like)",
    "family": "\"MD Cinzel\"",
    "cls": "display",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "merriweather",
    "label": "Merriweather",
    "family": "\"MD Merriweather\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "playfair",
    "label": "Playfair Display",
    "family": "\"MD Playfair Display\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "ptserif",
    "label": "PT Serif",
    "family": "\"MD PT Serif\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "lora",
    "label": "Lora",
    "family": "\"MD Lora\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "notoserif",
    "label": "Noto Serif",
    "family": "\"MD Noto Serif\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "sourceserif",
    "label": "Source Serif",
    "family": "\"MD Source Serif 4\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "ebgaramond",
    "label": "EB Garamond (Garamond)",
    "family": "\"MD EB Garamond\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "librebaskerville",
    "label": "Libre Baskerville (Baskerville)",
    "family": "\"MD Libre Baskerville\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "crimson",
    "label": "Crimson Text",
    "family": "\"MD Crimson Text\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "cormorant",
    "label": "Cormorant Garamond",
    "family": "\"MD Cormorant Garamond\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "spectral",
    "label": "Spectral",
    "family": "\"MD Spectral\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "domine",
    "label": "Domine",
    "family": "\"MD Domine\"",
    "cls": "serif",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "bitter",
    "label": "Bitter",
    "family": "\"MD Bitter\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "robotoslab",
    "label": "Roboto Slab",
    "family": "\"MD Roboto Slab\"",
    "cls": "serif",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "arvo",
    "label": "Arvo (Rockwell-like)",
    "family": "\"MD Arvo\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "zillaslab",
    "label": "Zilla Slab",
    "family": "\"MD Zilla Slab\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "breeserif",
    "label": "Bree Serif",
    "family": "\"MD Bree Serif\"",
    "cls": "serif",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "oldstandard",
    "label": "Old Standard TT (Century)",
    "family": "\"MD Old Standard TT\"",
    "cls": "serif",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "robotomono",
    "label": "Roboto Mono",
    "family": "\"MD Roboto Mono\"",
    "cls": "mono",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "sourcecodepro",
    "label": "Source Code Pro",
    "family": "\"MD Source Code Pro\"",
    "cls": "mono",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "plexmono",
    "label": "IBM Plex Mono",
    "family": "\"MD IBM Plex Mono\"",
    "cls": "mono",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "jetbrainsmono",
    "label": "JetBrains Mono",
    "family": "\"MD JetBrains Mono\"",
    "cls": "mono",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "inconsolata",
    "label": "Inconsolata (Consolas-like)",
    "family": "\"MD Inconsolata\"",
    "cls": "mono",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "spacemono",
    "label": "Space Mono",
    "family": "\"MD Space Mono\"",
    "cls": "mono",
    "hasItalic": true,
    "hasBold": true
  },
  {
    "id": "pacifico",
    "label": "Pacifico",
    "family": "\"MD Pacifico\"",
    "cls": "script",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "lobster",
    "label": "Lobster",
    "family": "\"MD Lobster\"",
    "cls": "script",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "dancingscript",
    "label": "Dancing Script",
    "family": "\"MD Dancing Script\"",
    "cls": "script",
    "hasItalic": false,
    "hasBold": true
  },
  {
    "id": "greatvibes",
    "label": "Great Vibes",
    "family": "\"MD Great Vibes\"",
    "cls": "script",
    "hasItalic": false,
    "hasBold": false
  },
  {
    "id": "satisfy",
    "label": "Satisfy",
    "family": "\"MD Satisfy\"",
    "cls": "script",
    "hasItalic": false,
    "hasBold": false
  }
];
