/**
 * Source of truth for the typefaces the image-text editor can match and draw.
 * [id, dropdown label, Google Fonts family name, class]
 *
 * After editing, run:  node scripts/fetch-edit-fonts.mjs
 */
export const FONT_LIST = [
  // --- metric-compatible clones of the system classics (always shortlisted)
  ["arimo", "Arial / Helvetica (Arimo)", "Arimo", "sans"],
  ["tinos", "Times New Roman (Tinos)", "Tinos", "serif"],
  ["cousine", "Courier New (Cousine)", "Cousine", "mono"],
  ["carlito", "Calibri (Carlito)", "Carlito", "sans"],
  ["caladea", "Cambria (Caladea)", "Caladea", "serif"],

  // --- sans
  ["roboto", "Roboto", "Roboto", "sans"],
  ["opensans", "Open Sans", "Open Sans", "sans"],
  ["lato", "Lato", "Lato", "sans"],
  ["inter", "Inter / San Francisco-like", "Inter", "sans"],
  ["sourcesans", "Source Sans", "Source Sans 3", "sans"],
  ["notosans", "Noto Sans", "Noto Sans", "sans"],
  ["montserrat", "Montserrat", "Montserrat", "sans"],
  ["poppins", "Poppins", "Poppins", "sans"],
  ["raleway", "Raleway", "Raleway", "sans"],
  ["nunito", "Nunito", "Nunito", "sans"],
  ["nunitosans", "Nunito Sans", "Nunito Sans", "sans"],
  ["ptsans", "PT Sans", "PT Sans", "sans"],
  ["worksans", "Work Sans", "Work Sans", "sans"],
  ["rubik", "Rubik", "Rubik", "sans"],
  ["firasans", "Fira Sans", "Fira Sans", "sans"],
  ["ubuntu", "Ubuntu", "Ubuntu", "sans"],
  ["barlow", "Barlow", "Barlow", "sans"],
  ["dmsans", "DM Sans", "DM Sans", "sans"],
  ["manrope", "Manrope", "Manrope", "sans"],
  ["mulish", "Mulish", "Mulish", "sans"],
  ["josefinsans", "Josefin Sans", "Josefin Sans", "sans"],
  ["quicksand", "Quicksand", "Quicksand", "sans"],
  ["kanit", "Kanit", "Kanit", "sans"],
  ["cabin", "Cabin", "Cabin", "sans"],
  ["titillium", "Titillium Web", "Titillium Web", "sans"],
  ["exo2", "Exo 2", "Exo 2", "sans"],
  ["librefranklin", "Libre Franklin (Franklin Gothic)", "Libre Franklin", "sans"],
  ["plexsans", "IBM Plex Sans", "IBM Plex Sans", "sans"],
  ["karla", "Karla", "Karla", "sans"],
  ["spacegrotesk", "Space Grotesk", "Space Grotesk", "sans"],
  ["outfit", "Outfit", "Outfit", "sans"],
  ["figtree", "Figtree", "Figtree", "sans"],
  ["archivo", "Archivo", "Archivo", "sans"],
  ["heebo", "Heebo", "Heebo", "sans"],
  ["hind", "Hind", "Hind", "sans"],
  ["asap", "Asap", "Asap", "sans"],
  ["signika", "Signika", "Signika", "sans"],
  ["varelaround", "Varela Round", "Varela Round", "sans"],
  ["comfortaa", "Comfortaa", "Comfortaa", "sans"],
  ["fredoka", "Fredoka (rounded)", "Fredoka", "sans"],
  ["baloo2", "Baloo 2", "Baloo 2", "sans"],

  // --- display / poster
  ["oswald", "Oswald (condensed)", "Oswald", "display"],
  ["bebasneue", "Bebas Neue", "Bebas Neue", "display"],
  ["anton", "Anton / Impact-like", "Anton", "display"],
  ["archivoblack", "Archivo Black", "Archivo Black", "display"],
  ["barlowcondensed", "Barlow Condensed", "Barlow Condensed", "display"],
  ["fjallaone", "Fjalla One", "Fjalla One", "display"],
  ["teko", "Teko", "Teko", "display"],
  ["staatliches", "Staatliches", "Staatliches", "display"],
  ["passionone", "Passion One", "Passion One", "display"],
  ["righteous", "Righteous", "Righteous", "display"],
  ["russoone", "Russo One", "Russo One", "display"],
  ["lilitaone", "Lilita One", "Lilita One", "display"],
  ["bangers", "Bangers (comic)", "Bangers", "display"],
  ["luckiestguy", "Luckiest Guy", "Luckiest Guy", "display"],
  ["alfaslab", "Alfa Slab One", "Alfa Slab One", "display"],
  ["abrilfatface", "Abril Fatface", "Abril Fatface", "display"],
  ["dmserifdisplay", "DM Serif Display", "DM Serif Display", "display"],
  ["cinzel", "Cinzel (Trajan-like)", "Cinzel", "display"],

  // --- serif
  ["merriweather", "Merriweather", "Merriweather", "serif"],
  ["playfair", "Playfair Display", "Playfair Display", "serif"],
  ["ptserif", "PT Serif", "PT Serif", "serif"],
  ["lora", "Lora", "Lora", "serif"],
  ["notoserif", "Noto Serif", "Noto Serif", "serif"],
  ["sourceserif", "Source Serif", "Source Serif 4", "serif"],
  ["ebgaramond", "EB Garamond (Garamond)", "EB Garamond", "serif"],
  ["librebaskerville", "Libre Baskerville (Baskerville)", "Libre Baskerville", "serif"],
  ["crimson", "Crimson Text", "Crimson Text", "serif"],
  ["cormorant", "Cormorant Garamond", "Cormorant Garamond", "serif"],
  ["spectral", "Spectral", "Spectral", "serif"],
  ["domine", "Domine", "Domine", "serif"],
  ["bitter", "Bitter", "Bitter", "serif"],
  ["robotoslab", "Roboto Slab", "Roboto Slab", "serif"],
  ["arvo", "Arvo (Rockwell-like)", "Arvo", "serif"],
  ["zillaslab", "Zilla Slab", "Zilla Slab", "serif"],
  ["breeserif", "Bree Serif", "Bree Serif", "serif"],
  ["oldstandard", "Old Standard TT (Century)", "Old Standard TT", "serif"],

  // --- mono
  ["robotomono", "Roboto Mono", "Roboto Mono", "mono"],
  ["sourcecodepro", "Source Code Pro", "Source Code Pro", "mono"],
  ["plexmono", "IBM Plex Mono", "IBM Plex Mono", "mono"],
  ["jetbrainsmono", "JetBrains Mono", "JetBrains Mono", "mono"],
  ["inconsolata", "Inconsolata (Consolas-like)", "Inconsolata", "mono"],
  ["spacemono", "Space Mono", "Space Mono", "mono"],

  // --- script (typeset scripts, not handwriting)
  ["pacifico", "Pacifico", "Pacifico", "script"],
  ["lobster", "Lobster", "Lobster", "script"],
  ["dancingscript", "Dancing Script", "Dancing Script", "script"],
  ["greatvibes", "Great Vibes", "Great Vibes", "script"],
  ["satisfy", "Satisfy", "Satisfy", "script"],
];
